Website/Logbook/urls.py
from django.conf.urls import url
from . import views
app_name ='Logbook'
urlpatterns = [
    url(r'^', views.IndexView.as_view(), name = 'index'),
    url(r'^?P<log_id>[0-9]+)/$'), views.EntryView.as_view(), name = 'entry'),
]

Website/Website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('Logbook.urls')),
]

Website/Logbook/models.py
from django.db import models
from django.contrib.auth.models import Permission, User

class Log(models.Model):
    user = models.ForeignKey(User, default = 1)
    log_title = models.CharField(max_length = 20)
    log_category = models.CharField(max_length = 20)
    log_date = models.DateTimeField()

    def __str__(self):
        return self.log_title

class Entry(models.Model):
    log = models.ForeignKey(Log, on_delete=models.CASCADE)
    title = models.CharField(max_length = 20)
    text = models.CharField(max_length = 500, default = "None")
    date = models.DateTimeField()

    def __str__(self):
        return self.title

Website/Logbook/views.py
from django.views import generic
from django.http import Http404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .models import Log, Entry
import datetime
from django.db.models import Q

class IndexView(generic.ListView):
    template_name = 'Logbook/index.html'
    context_object_name = 'all_logs'

    def get_queryset(self):
        return Log.objects.all()

class EntryView(generic.ListView):
    template_name = 'Logbook/entries.html'
    context_object_name = 'all_entries'

    def get_queryset(self):
        return Entry.objects.all()

# Create your views here.

Website/Logbook/templates/Logbook/base.html
<!DOCTYPE html>

<html lang = "en">
<head>
  <meta charset="utf-8" />
  <title>Team 5</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="Logbook/css" href="{% static 'Logbook/style.css' %}"/>
</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Logbook:index' %}">Team 5</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block logs_active %}{% endblock %}"><a href="{% url 'Logbook:index' %}"><span class="glyphicon glyphicon-road" aria-hidden="true"></span>&nbsp; Logs</a></li>
                <li class="{% block entrys_active %}{% endblock %}"><a href="#"><span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Entries</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'Logbook:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="#">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Log
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>

</html>

Website/Logbook/templates/Logbook/entries.html
{% extends 'Logbook/base.html' %}
{%block body%}
        {% for log in all_logs %}
        <div class="col-sm-4 col-lg-2">
                  <div class="thumbnail">
                      <h2><a href="#">
                          {{ log.log_title }} <small>  by {{log.user}}</small>
                      </a></h2>
                      <h5>created on: <br> {{log.log_date}}</h5>
                      <div class="caption">
                          <!-- View Details -->
                          <a href="#" class="btn btn-primary btn-sm" role="button">View Details</a>

                      </div>
                  </div>
              </div>
        {% endfor %}
{%endblock%}

Website/Logbook/templates/Logbook/index.html
{% extends 'Logbook/base.html' %}
{%block body%}
        {% for log in all_logs %}
        <div class="col-sm-4 col-lg-2">
                  <div class="thumbnail">
                      <h2><a href="#">
                          {{ log.log_title }} <small>  by {{log.user}}</small>
                      </a></h2>
                      <h5>created on: <br> {{log.log_date}}</h5>
                      <div class="caption">
                          <!-- View Details -->
                          <a href="#" class="btn btn-primary btn-sm" role="button">View Details</a>

                      </div>
                  </div>
              </div>
        {% endfor %}
{%endblock%}